2018-08-21 22:18:12,252 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 22:20:01,481 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 22:22:52,046 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 22:22:54,928 ERROR: Exception on /login [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/root/microblog_tryout/app/routes.py", line 55, in gs
    user = User.query.filter_by(username=username).first()
NameError: global name 'username' is not defined
2018-08-21 22:41:55,804 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 22:43:39,690 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 22:43:47,943 ERROR: Exception on /index [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/root/microblog_tryout/app/routes.py", line 28, in index
    return render_template("index.html", title='Home Page', posts=posts, user_title=user_title)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/microblog_tryout/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/root/microblog_tryout/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/root/microblog_tryout/app/templates/index.html", line 8, in block "content"
    <form action="{{ url_for('gs') }}" method="post">
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'gs'. Did you mean 'register' instead?
2018-08-21 22:43:53,222 ERROR: Exception on /index [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/root/microblog_tryout/app/routes.py", line 28, in index
    return render_template("index.html", title='Home Page', posts=posts, user_title=user_title)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/microblog_tryout/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/root/microblog_tryout/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/root/microblog_tryout/app/templates/index.html", line 8, in block "content"
    <form action="{{ url_for('gs') }}" method="post">
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'gs'. Did you mean 'register' instead?
2018-08-21 22:51:54,181 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 22:53:25,873 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 22:53:32,857 ERROR: Exception on /gettingstarted [POST] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/root/microblog_tryout/app/routes.py", line 55, in gs
    user = User.query.filter_by(username=username).first()
NameError: global name 'username' is not defined
2018-08-21 22:54:25,905 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 22:54:32,000 ERROR: Exception on /gettingstarted [POST] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
TypeError: gs() takes exactly 1 argument (0 given)
2018-08-21 22:55:36,285 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 23:04:10,779 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 23:07:02,121 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 23:07:31,347 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 23:13:22,380 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 23:15:16,602 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 23:19:01,898 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 23:19:50,226 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
2018-08-21 23:21:58,008 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:45]
