2018-08-25 00:27:48,002 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:51]
2018-08-25 00:29:37,173 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:51]
2018-08-25 00:33:25,336 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:51]
2018-08-25 00:38:06,882 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:51]
2018-08-25 00:41:13,935 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:51]
2018-08-25 00:42:55,681 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:51]
2018-08-25 01:08:52,122 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:51]
2018-08-25 01:08:56,021 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:51]
2018-08-25 01:09:11,128 ERROR: Exception on /reset_password_request [POST] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/microblog_tryout/app/routes.py", line 223, in reset_password_request
    send_password_reset_email(user)
  File "/root/microblog_tryout/app/email.py", line 9, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: global name 'app' is not defined
2018-08-25 01:10:58,140 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:51]
2018-08-25 01:11:08,952 ERROR: Exception on /reset_password_request [POST] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/microblog_tryout/app/routes.py", line 224, in reset_password_request
    send_password_reset_email(user)
  File "/root/microblog_tryout/app/email.py", line 9, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: global name 'app' is not defined
2018-08-25 01:12:28,423 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:51]
2018-08-25 01:22:55,193 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:51]
2018-08-25 01:24:07,984 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:51]
2018-08-25 01:28:20,075 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:51]
2018-08-25 01:36:10,113 INFO: Microblog startup [in /root/microblog_tryout/app/__init__.py:51]
2018-08-25 13:45:22,614 INFO: Microblog startup [in /root/code/precocite/app/__init__.py:51]
